[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "jinja2>=3.1.6",
    "pillow>=11.3.0",
    "pyautogui>=0.9.54",
    "requests>=2.32.4",
    "selenium>=4.34.2",
]
